### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by jackstruck** [DilanTsasi/jodit-vue3#1]
This error is triggered by https://github.com/DilanTsasi/jodit-vue3/blob/717a8aea3b44cd7fc0208b0f63fe9b23985a4050/src/JoditEditor.vue#L54
`
this.editor.value = this.modelValue;
`
If I comment it out, I get no errors and the editor components render without an issue. However, the value of the passed v-model tag doesn't reflect in the editor. Any suggestions?

**Comment by DilanTsasi** [comment]
How are you importing/using the library
share more details

plus the reason why you don't get any in the editor is that you have commented out the line meant to set the editor value

**Comment by jackstruck** [comment]
Yeah, definitely an important line for that reason. However when when that line is uncommented I get the error and still no value.

I am importing the library by directly including the files within my build. My file structure looks like this:
-JoditEditor.vue <- Local copy of your file
-TextGenerator.vue <- Editor called here

Within my TextGenerator.vue file, I call the library with the following in the script section:
```
import JoditEditor from "./JoditEditor.vue";
export default {
  name: "TextGenerator",
  //...
  components: {
    JoditTemplateEditor: JoditEditor,
  },
```

And the following within the <template> tags:
`<jodit-template-editor
                          id="template-editor"
                          class="form-control"
                          name="template-editor"
                          v-model="content"
                          @input="dirtState"
                        ></jodit-template-editor>
`

**Comment by DilanTsasi** [comment]
In that case, you will have to manually install Todit editor as the wrapper depends on Jodit Editor
https://www.npmjs.com/package/jodit

**Comment by jackstruck** [comment]
I am importing Jodit Pro in my local copy of your JoditEditor.vue file as:
`import { Jodit } from "jodit-pro";`
Am I missing anything else?

**Comment by DilanTsasi** [comment]
I will have to get a sample of your code in order to be able to reproduce the issue
